version: '3.8'
name: vibelens-music-crawler

services:

  music-crawler:
    build:
      context: ./music_crawler
      dockerfile: Dockerfile
    container_name: music-crawler
    restart: unless-stopped
    volumes:
      - ./music_crawler:/usr/src/app

  cache-crawl:
    image: bitnami/redis:7.4.2
    container_name: cache-crawl
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  cache-data:
    driver: local