version: '3.8'
name: vibelens-music-crawler

services:
  store-and-download-music-worker:
    build:
      context: ./store_and_download_music
      dockerfile: Dockerfile
    container_name: store-and-download-worker
    restart: unless-stopped
    volumes:
      - ./store_and_download_music:/usr/src/app
    depends_on:
      - vector-database
      - cache-crawl
    networks:
      - shared-network

  database:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vibelens
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/

  pgadmin-crawler:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin-crawler
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database


  vector-database:
    image: qdrant/qdrant:v1.13.6
    container_name: vector-database
    ports:
      - "6333:6333"   # HTTP API port
      - "6334:6334"   # gRPC port
    restart: always
  

volumes:
  vector-data:
    driver: local
  