version: '3.8'
name: vibelens-music-crawler

services:
  download_music:
    build:
      context: ./download_music
      dockerfile: Dockerfile
    container_name: download_music
    restart: unless-stopped
    environment:
      KAFKA_URI: kafka:29092
      KAFKA_TOPIC: crawl-song
      KAFKA_GROUP_ID: 1
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: test
    volumes:
      - ./download_music:/usr/src/app
    networks:
      - vibelens-shared-network
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001" # MinIO Console
    networks:
      - vibelens-shared-network

networks:
  vibelens-shared-network:
    external: true