version: '3.8'
name: vibelens-music-crawler

services:
  store-and-download-music-worker:
    build:
      context: ./store_and_download_music
      dockerfile: Dockerfile
    container_name: store-and-download-worker
    restart: unless-stopped
    volumes:
      - ./store_and_download_music:/usr/src/app
    depends_on:
      - vector-database
      - cache-crawl
    networks:
      - shared-network


  vector-database:
    image: qdrant/qdrant:v1.13.6
    container_name: vector-database
    ports:
      - "6333:6333"   # HTTP API port
      - "6334:6334"   # gRPC port
    restart: always
  

volumes:
  vector-data:
    driver: local
  